---
title: reflections on the rittenhouse verdict and discourse
author: Nash Sauter
date: '2021-11-20'
slug: rittenhouse
categories: []
tags: []
---

I understand that right now is a very emotional and important time for members of marginalized groups and members of the political left as a whole, however I do feel like it is important to evaluate our collective response to the events surrounding the shootings in Kenosha. While what I believe to be the truth of the matter does go against what seems to be commonly held beliefs of people I know on the left, this is in no way meant to antagonize or demerit the Black Lives Matter movement, or any of the other related groups that are seek to create a better future for those that have been harmed for generations as a result of oppressive systems.

## Prosecution and The Criminal Justice System

We have seen time and time again that the criminal justice system is full of injustice. Innocent people, especially minorities, get thrown in jail for crimes that they didn’t do and can even be sentenced to death through the whims of biased juries and state prosecutors. White supremacy is prevalent in our criminal justice system from policing, to courtrooms, to prisons and everywhere in between. Studies show that black men will receive longer sentences than white counterparts for comparable crimes. We have seen that republican-appointed judges give longer sentences than democratic-appointed judges to black defendants. It is likely that if Rittenhouse were a black man, he would have received much harsher treatment and might have even been ruled as guilty. Along these lines, the current system of retributive justice as a whole is unjust and ineffective. The role of prosecutors is not to create a better society by punishing bad guys, it is to get a guilty verdict. 

Despite this, I have seen countless instances of people who believe Rittenhouse was in the wrong perpetuating the narratives of our justice system. Thomas Binger, the lead prosecutor isn’t some kind of unique bringer of justice, he is a state prosector. While he has spoken of prosecuting child molesters and other such criminals, he has also prosecuted against drug dealers. I’m not going to pretend to know everything about his history, but his position involves pursuing a guilty verdict by any means possible according to the laws made by the state. This role is the same regardless of whether he is pursuing charges on a murderer or a victimless drug user. 

As expected, he has attempted to create bias in the minds of the jury by means outside of what is within the grounds of the trial. He has brought up Rittenhouse’s refusal to speak in a prior point in time, which is covered by the 5th Amendment. Regardless of what you think about Rittenhouse, these protections exist for a reason, and that is to prevent innocent people from being ruled guilty due to jury bias. He has repeatedly ignored the impact of video compression artifacts and upscaling algorithms on the admissibility of video evidence, which is especially important when someone’s guilt can come down to a few pixels. For example, the prosecution sent a heavily compressed version of an important piece of evidence to the defense, which was visibly different from the file that was sent to the state crime lab (from 11 MB to 4 MB) and then tried to act as if it was a fault on the part of the defense. This is not to say that these things are necessarily malicious or anything of the sort (although it is possible that is the case). I am simply saying that the same criticisms that we apply to criminal prosecutors in general should also be applied in cases such as this one and that blindly believing the prosecution narrative in any case is inherently harmful, regardless of how the case might appear on the surface.

## Accusations of Judge Bias

I have seen people who are saying that the verdict of the case, where Rittenhouse has been ruled as not guilty on all charges, is due to a bad judge or ideas that are similar to that. For example, the judge ruled that the victims in this case could not be labelled as “victims” in front of the jury. While it could certainly be seen as an odd ruling, the whole point of it is to prevent the jury from being biased due due to non-fact matters and it seems to be similar to the way that this judge has treated trials in the past. Of course I can’t comment to the degree in which this is unusual since I am not a trial lawyer, but this alone is not nearly enough evidence to suggest any bias towards Rittenhouse that can’t be explained by the general bias towards the defense that comes from idea that someone is innocent until proven guilty. It is of course possible that the judge is biased in some ways as are judges in general, but I haven’t seen any convincing argument that this has affected the trial in any kind of meaningful manner.

## Retribution and Causality

One reason that I have brought all of this up is because I have seen an alarming amount of emotional investment in the potential for a guilty verdict. This is understandable considering the context of the events that were happening when the shooting happened. However, that should not mean that we should ignore the ways in which our injustice is present in our legal system. I am against the current system of retributive justice, where we simply base punishment on narratives of revenge while ignoring rates of recidivism. I am against a system where we lock people up and assume it’s going to teach them a lesson instead of providing help to people and addressing the conditions that lead to harm. This is no different in the case regarding the Kenosha shooting. Putting all of the blame on a 17-old-kid instead of speaking at all about the conditions that led to these tragic events is simply ineffective and misdirected. Every crime has a set of underlying causes and circumstances behind it, and ignoring the circumstances in favor of hating an individual for happening to be affected by those circumstances doesn’t really make much sense. For example, I am surprised that we haven’t seen more discussion about the nature of gun ownership laws and how they allowed a 17-year-old to legally carry an AR-15.

Even if we were to believe the worst possible narrative (which I will partially address in the next section) that Rittenhouse was an explicit white nationalist that travelled to a completely unrelated location across an entire state for the planned purpose of killing protestors with a gun that he knew was illegal, there would still be problems with the ways in which many people are addressing the case. Saying that he should rot in prison and leaving it there would just contribute to the false narrative that locking the bad people in prison is the ultimate goal of a justice system, while in reality the goal should be to actually fix the underlying issues and rehabilitate the people that have been affected by them, both on the side of the victim and the offender. Additionally, instead of blaming a 17-year-old for holding white supremacist views, it would instead be better to blame those who radicalized him into believing them. People aren’t born thinking that white people are superior, they are taught that over time. If you claim to believe in the powerful force of the alt-right pipeline, then you shouldn’t be blaming vulnerable people for falling for those tactics.

## Misinformation and Needless Speculation

On a final note, I’d like to address the details of the case more specifically. I have seen countless amounts of people talking about the various facts of the case since it happened. Although I believe that everyone I know is acting in good faith, the framing on this case has been vastly misrepresented. To give a few examples, people have repeatedly been saying that Rittenhouse “traveled across state lines” as an argument against him. While this is literally true, focusing on this and using this phrasing is clearly misleading. First, Antioch, Illinois is right near the border of Wisconsin. It’s about a 35 minute drive from Kenosha, which is pretty insignificant. Second, Rittenhouse seemed to have a decent amount of connections with Kenosha. For example, he worked there as a lifeguard and in all likelihood had various connections there. Third, it doesn’t even seem to matter that he crossed state lines in the first place. I would agree that it was really dumb for him to travel there during the peak of the rioting in order to defend property and there in all likelihood should have been prevented from doing so by his parents. However, this isn’t nearly enough to say that he had intent to kill people.

On the question of self defense, the question is not being brought up nearly as much by the left-wing people I know. In all three deaths, it seems completely reasonable that Rittenhouse would believe his life was being threatened. In the first case, a man was chasing after him while he had a gun in hand and seemed to be reaching towards the barrel of the gun. In the other cases, he was kicked and hit by a skateboard, and could have reasonably believed that they were trying to knock him to the ground. Of course, I can’t tell you exactly what he was thinking since I’m not him, and it’s completely possible that he wanted to kill them. If there was evidence that he put himself in those situations for the purpose of provoking people into attacking him, then it would not be self-defense. However, that evidence is not apparent, and therefore we cannot know what he was thinking. Anyone that is saying exactly what his motive was is being dishonest. Of course we can speculate based on his interactions with Proud Boys or his actions prior to that night, but that is still just weak speculation.

Additionally, I’d like to speak on the topic of Rittenhouse’s tears during the trial. It’s possible that the tears were fake, but treating that as some kind of completely obvious fact is dishonest. He was 17 years old and he killed 3 people in about 6 minutes. I really don’t see a reason as to why completely unreasonable to think that someone would have a panic attack while having to recall those events in a heavily publicized trial.

## Conclusion

At the end of the day, no one can be certain about what Kyle Rittenhouse was thinking on that day. I would agree that in the even in the best case scenario, we can see that Rittenhouse clearly did something really dumb by choosing to bring a gun to an already volatile scene. However, we cannot be sure with our current evidence about whether or not his intent was worse than that, and as a result it would be unjust to punish him. The same thing goes with the judge, in that we can't tell if he was truly biased towards Rittenhouse. However, one thing we can be more certain about is the root causes behind those events. We can be sure that the a police officer killed a black man, which led to the riots. We can be sure that those riots caused enough of a threat to private property that a group of people felt the need to defend that property by threat of lethal force. We can be sure that a 17-year-old kid possessed an AR-15 and was convinced to join the group that of people that were doing that. We can also know that this case would have been treated very differently had the race of the defendant been different. However, just repeating the notion that this is just another case where a white guy gets away with murder isn't productive or helpful. There are plenty of cases of that exact scenario that happen already, and there's no point in lumping this one in with them. I would encourage you to donate to any of the following groups or any related groups you know of if you have the means to do so.

### Links
https://www.gofundme.com/f/kenosha-recovery-fundraiser
https://innocenceproject.org/
https://www.sentencingproject.org/about-us/