---
title: albums from 2021 that you should listen to
author: Nash Sauter
date: '2022-03-28'
slug: 2021albums
categories: []
tags: []
description: "my 10 favorite albums of the year"
---

Now that it's been a four months since the end of 2021, it's about time to recap some of the my favorite albums of the year. Here's my top 10 favorites along with six honorable mentions.

## 10. Welfare Jazz - Viagra Boys (post-punk)
Welfare Jazz is the second album from Swedish post-punk band Viagra Boys. The album features noisy instrumentals alongside rambunctious vocals dealing with pessimistic topics of burnout and failure in urban society. In a sarcastic and raw manner, the music addresses these ideas by playing up their absurdity, often to a humorous extent. The first song of the album Ain't Nice deals with masculine overcompensation, with the singer taking the role of a man trying to prove how tough and mean he is despite his vintage calculator collection and hunger for snacks.

[**Ain't Nice**](https://youtu.be/vzWds5gWS6c)

[**Album Link**](https://album.link/us/i/1533668629)

## 9. Jubilee - Japanese Breakfast (dream pop)
Jubilee, the third album by Michelle Zauner under the name Japanese Breakfast, is a warm and reflective dream pop that shines through its wide variety of instrumentations and dynamic singing. Through the groovy upbeat synths found in Be Sweet and the solemn strings of Tactics, Jubilee captures all the shades of happiness that appear in longing, love, and introspection.

[**Be Sweet**](https://youtu.be/yNUO6MFaUnM)

[**Album Link**](https://album.link/us/i/1553364590)

## 8. Home Video - Lucy Dacus (singer-songwriter, indie rock)
Home Video, the third album by Lucy Dacus, is a bittersweet series of intricate stories primarily about adolescent love. The driving drum backings found on songs like Hot & Heavy and VBS create a catchy indie-rock backing while Lucy Dacus exposes her inner thought processes with sentimental lyrics about flawed romances.

[**VBS**](https://youtu.be/u8JqjG8A90g)

[**Album Link**](https://album.link/us/i/1586471742)

## 7. Mercurial World - Magdalena Bay (synthpop)
L.A. based synthpop duo Magdalena Bay's debut album is a fantastic series of electronic music. The ethereal synth backings and the hypnotic voice of singer Mica Tenenbaum combine to create an album that'll make you lose track of time in an instant. The songs are consistent, but don't get boring. They embrace the new sounds of the internet era, but have hints of retro style mixed in to create a unique sound.

[**Dawning of the Season**](https://youtu.be/OujNh58WEQ0)

[**Album Link**](https://album.link/us/i/1570541671)

## 6. Sling - Clairo (singer-songwriter, chamber folk)
Bedroom pop phenomenon Clairo's second album is a collection of singer-songwriter, soft-rock, and folk styles all delivered together in a neat package. Claire Cottrill's poetic writing and beautiful delivery contrast from the homemade pop feel of her earlier work, showing that she's truly talented at creating music regardless of what form it takes. One of the reccuring themes that Claire addresses are the problems of emotional exhaustion that comes with being a woman in the music industry. For example, Blouse deals with the objectification of women by men in the industry, and Amoeba deals with the stresses of constantly touring.

[**Amoeba**](https://youtu.be/7WXXaIz3uds)

[**Album Link**](https://album.link/us/i/1571215405)

## 5. Glow On - Turnstile (punk rock, hardcore)
Glow On is an energetic and lively hardcore album by the band Turnstile. While the upfront guitar riffs and aggresive vocals take up a lot of the listener's attention, the sound often shifts into feeling surreal and dreamy. This is notably prominent on the song ALIEN LOVE CALL which features a vocal performance from the alt. r&b musician Blood Orange. These contrasts often appear even within single tracks, such as in UNDERWATER BOI and MYSTERY. The variety of sounds across the album manage to compliment each other well rather than clashing, and as a result creates one of the most engaging albums of the year.

[**MYSTERY**](https://youtu.be/1Ny1fjdLKew)

[**Album Link**](https://album.link/us/i/1576430192)

## 4. Collapsed in Sunbeams - Arlo Parks (neo-soul, bedroom pop)
Collapsed in Sunbeams is the debut album of British artist Arlo Parks. The album shines through it's mellow story telling and fantastic r&b musical tracks. The backings are full and lush, but don't overpower the often soft-spoken voice Arlo Parks. The lyrical writing is specifically strong in some sections due to the present-tense phrasing, making the listener feel like they are watching the scene unfold in front of them.

[**Black Dog**](https://youtu.be/QOu0Ht0-D4M)

[**Album Link**](https://album.link/us/i/1534718812)

## 3. To See the Next Part of the Dream - Parannoul (shoegaze, emo)
To See the Next Part of the Dream is the first album from the Korean shoegaze artist Parannoul. The cold and cloudy atmosphere of the album is at the forefront, with noisy yet lofi instrumentals complementing the longing voice of the singer. You don't need to speak the language to understand and connect to the depressive nature of the lyrics.

[**Beautiful World**](https://youtu.be/gb9Qqt75rzg)

[**Album Link**](https://album.link/us/i/1563369236)

## 2. I Know I'm Funny haha - Faye Webster (indie folk, soft rock)
Atlanta-based artist Faye Webster's fourth album is a soothing indie album with some great folk and country aspects. In one of the most laid-back albums of the year, Faye Webster's soothing voice is accompanied by simple soulful instrumentals. While the album borders on being formulaic, it's manages to stay as one of my favorites of the year because the formula is so good. The songs are easy to get stuck in your head and can easily be listened to on repeat.

[**A Dream with a Baseball Player**](https://youtu.be/0VVjgdY-Fw8)

[**Album Link**](https://album.link/us/i/1561398236)

## 1. The Path of the Clouds - Marissa Nadler (dream pop, psychedelic folk)
Boston-based folk artist Marissa Nadler's ninth solo album, The Path of the Clouds, is one of her most ambitious projects to date. Contrasted to the her 2018 album For My Crimes (which still remains as one of my favorite albums) which was stripped back and often solely featured Marissa Nadler's wispy voice with a guitar strumming in the background, The Path of The Clouds is full of vapory dream-pop backings with lush folk instrumentation. The landscapes that Nadler produces are engaging and adventurous. In the opening track, Bessie Did You Make It, Nadler starts off with the typical guitar backing that can be found across many of her albums, but builds into a full dreary soundscape that accompanies her unique form of a murder ballad. The next track, titled The Path of the Clouds makes the listener feel like they're up in the sky, as Nadler sings from the perspective of D.B. Cooper jumping out of a plane. These vivid pictures continue throughout the rest of the album, creating what feels like visual art in the form of music. The dream pop, folk, gothic country, and psychedelic factors in this album all mesh together perfectly to create my favorite album of the year.

[**The Path of the Clouds**](https://youtu.be/KJbPs0-6U68)

[**Album Link**](https://album.link/us/i/1578892841)

### Honorable Mentions
* Cull Ficle - Asian Glow
* Friends That Break Your Heart - James Blake
* Last Year Was Weird, Vol. 3 - Tkay Maidza
* Cavalcade - black midi
* Muscle Memories - arigarnon friend's
* ENTERTAINMENT, DEATH - SPIRIT OF THE BEEHIVE
